### ISSUE TITLE
Очень непонятная численная константа

### ISSUE THREAD

**Issue by hastyulia** [voteslaugh/Typing_trainer#11]
https://github.com/voteslaugh/Typing_trainer/blob/7c376e57f51d623b28ed92d907f09cdcbe61f1ab/trainer/window/logic/line_handler.py#L36

Вынести в константу и в конфиг файл ее

**Comment by Ananastyyy** [comment]
Для выноса в файл конфиг нужно воспользоваться модулем configparser или есть какой-то другой способ?

**Comment by Ananastyyy** [comment]
@hastyulia 
Для выноса в файл конфиг нужно воспользоваться модулем configparser или есть какой-то другой способ?

**Comment by Ananastyyy** [comment]
И в файл с каким расширением лучше записывать все эти константы?

**Comment by hastyulia** [comment]
> Для выноса в файл конфиг нужно воспользоваться модулем configparser или есть какой-то другой способ?

Не обязательно. Всякие константы можно хранить в .py файлах, а вот с секретными/приватными данными так поступать нельзя. Они не должны оказываться в репозитории
