### ISSUE TITLE
А в папке resources что-то должно быть?

### ISSUE THREAD

**Issue by hastyulia** [voteslaugh/Typing_trainer#16]
https://github.com/voteslaugh/Typing_trainer/tree/main/resources

**Comment by Ananastyyy** [comment]
@hastyulia там лежит музыка, которую я не добавила в гит) Стоит её залить?

**Comment by hastyulia** [comment]
> @hastyulia там лежит музыка, которую я не добавила в гит) Стоит её залить?

Либо залить какой нибудь файл, либо удалить папку. Если удалять папку, то стоит в readme указать, что вот в конфете есть такое то поле, в нем надо указать путь до папки, где у вас лежит музыка
