### ISSUE TITLE
Названия файлов должно быть в snake_case

### ISSUE THREAD

**Issue by hastyulia** [voteslaugh/Typing_trainer#22]
https://github.com/voteslaugh/Typing_trainer/blob/main/trainer/window/gui/widgets/keyboardButton.py

**Comment by Ananastyyy** [comment]
@hastyulia Ты имеешь ввиду пятую строку?

**Comment by hastyulia** [comment]
> @hastyulia Ты имеешь ввиду пятую строку?

Нет, я имею в виду сам файл, на который приложила ссылку
