### ISSUE TITLE
Лучше этот словарик вынести в константу и в отдельный файл с константами

### ISSUE THREAD

**Issue by hastyulia** [voteslaugh/Typing_trainer#8]
https://github.com/voteslaugh/Typing_trainer/blob/7c376e57f51d623b28ed92d907f09cdcbe61f1ab/trainer/window/logic/database_handler.py#L31

**Comment by Ananastyyy** [comment]
@hastyulia 
Этот словарь не является константным, ведь в нем во время работы программы меняются поля. Я могу вынести только ключи этого словаря.
